# Generated by Django 4.2.3 on 2023-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.CharField(blank=True),
        ),
    ]
