# Generated by Django 4.2.3 on 2023-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
